name: dartway_tinkoff_serverpod_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 2.1.5
  crypto: ^3.0.6

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
